[postgres]
host = melnk-db.iii.com
port = 1032
database = iii
user = [username]
password = [password]

# SSL settings
sslmode = require

# logging
application_name = innreach_export
connect_timeout = 10


[email]
smtp_server = smtp.gmail.com
smtp_port = 587
username = lynn.uhlman@maineinfonet.org
password = [password]
from_email = lynn.uhlman@maineinfonet.org
to_emails = lynn.uhlman@maineinfonet.org,james.jacksonsanborn@maineinfonet.org
use_tls = true
